// Generated by CoffeeScript 1.10.0
var Card, Classes, Cover, React, moment;

React = require('react');

moment = require('moment');

Classes = require('shiny').Classes;

Card = React.createClass({
  displayName: 'Card',
  propTypes: {
    children: React.PropTypes.oneOfType([React.PropTypes.element, React.PropTypes.arrayOf(React.PropTypes.element)]).isRequired,
    link: React.PropTypes.string,
    id: React.PropTypes.string,
    title: React.PropTypes.string,
    target: React.PropTypes.string,
    className: React.PropTypes.oneOfType([React.PropTypes.string, React.PropTypes.object])
  },
  render: function() {
    var tag, variants;
    variants = new Classes();
    if (this.props.link) {
      tag = 'a';
      variants.set('link');
    } else {
      tag = 'div';
    }
    return React.createElement(tag, {
      id: this.props.id,
      className: "Card " + (this.props.className || '') + " " + variants,
      href: this.props.link,
      title: this.props.title,
      target: this.props.target
    }, this.props.children);
  }
});

module.exports = Card;
