// Generated by CoffeeScript 1.10.0
var React;

React = require('react');

module.exports = React.createClass({
  displayName: 'ContactForm',
  render: function() {
    var meta;
    if (this.props.meta) {
      meta = JSON.stringify(this.props.meta);
    }
    return React.createElement("div", {
      "className": 'ContactForm',
      "data-publication": global.config.PUBLICATION_SHORT_NAME,
      "data-commit": global.build_info.commit,
      "data-host": this.props.host,
      "data-meta": meta
    });
  }
});
