// Generated by CoffeeScript 1.10.0
var React;

React = require('react');

module.exports = React.createClass({
  displayName: '_Info',
  render: function() {
    return React.createElement("div", {
      "className": '_Info'
    }, this.props.children);
  }
});
