// Generated by CoffeeScript 1.10.0
var React;

React = require('react');

module.exports = React.createClass({
  displayName: '_Summary',
  render: function() {
    return React.createElement("p", {
      "className": '_Summary'
    }, this.props.summary);
  }
});
