// Generated by CoffeeScript 1.10.0
var React, Tags;

React = require('react');

Tags = React.createClass({
  displayName: 'Tags',
  propTypes: {
    tags: React.PropTypes.arrayOf(React.PropTypes.shape({
      slug: React.PropTypes.string,
      name: React.PropTypes.string
    }))
  },
  render: function() {
    var ref;
    return React.createElement("div", {
      "className": 'Tags'
    }, (ref = this.props.tags) != null ? ref.map(function(t) {
      return React.createElement("span", {
        "className": '_Tag',
        "data-slug": t.slug
      }, t.name);
    }) : void 0);
  }
});
