// Generated by CoffeeScript 1.10.0
var Classes, React;

React = require('react');

Classes = require('shiny').Classes;

module.exports = React.createClass({
  displayName: '_Title',
  propTypes: {
    title: React.PropTypes.oneOfType([React.PropTypes.string, React.PropTypes.array]),
    level: React.PropTypes.oneOf([1, 2, 3, 4, 5, 6]),
    link: React.PropTypes.string
  },
  getDefaultProps: function() {
    return {
      level: 3
    };
  },
  render: function() {
    var contents, cx, tag;
    tag = "h" + this.props.level;
    cx = new Classes('_Title', this.props.className);
    if (this.props.link) {
      contents = React.createElement("a", {
        "className": '_TitleLink',
        "href": this.props.link
      }, this.props.title);
      cx.add('link');
    } else {
      contents = this.props.title;
    }
    return React.createElement(tag, {
      className: cx
    }, contents);
  }
});
