// Generated by CoffeeScript 1.10.0
var Classes, React;

React = require('react');

Classes = require('shiny').Classes;

module.exports = React.createClass({
  displayName: 'CardGrid',
  propTypes: {
    columns: React.PropTypes.oneOf([1, 2, 3, 4]).isRequired,
    double_first: React.PropTypes.bool,
    double_last: React.PropTypes.bool,
    id: React.PropTypes.string,
    respond_to_viewport: React.PropTypes.bool,
    vary: React.PropTypes.bool
  },
  getDefaultProps: function() {
    return {
      columns: 3,
      double_first: false,
      double_last: false,
      respond_to_viewport: false,
      vary: true
    };
  },
  render: function() {
    var cx, items;
    cx = new Classes('CardGrid__', this.props.className);
    cx.set('columns', this.props.columns);
    cx.add('double_first', this.props.double_first);
    cx.add('double_last', this.props.double_last);
    cx.add('vary', this.props.vary);
    cx.add('respond_to_viewport', this.props.respond_to_viewport);
    items = this.props.children || this.props.items;
    return React.createElement("div", {
      "className": cx,
      "id": this.props.id
    }, React.Children.map(items, (function(_this) {
      return function(item, i) {
        return React.createElement("div", {
          "className": "_GridItem__",
          "key": _this.props.id + "_" + i
        }, item);
      };
    })(this)));
  }
});
